### ISSUE TITLE
can't delete FSM elements on macos

### ISSUE THREAD

**Issue by YasPHP** [evanw/fsm#24]
The instructions outlined: "Delete something: click it and press the delete key (not the backspace key)". There's isn't a delete button on mac, just backspace. Can ya add another delete command too (b/c it sometimes doesn't work, even when one presses the function (fn) and backspace key at the same time on mac)?

**Comment by YasPHP** [comment]
created a PR #25 to resolve this ^

**Comment by Anonym234** [comment]
you can "type" a delete key with fn-backspace on macOS

**Comment by YasPHP** [comment]
yup, thanks!
