### ISSUE TITLE
overlapping back-and-forth edges/transitions

### ISSUE THREAD

**Issue by Anonym234** [evanw/fsm#29]
if there are two states and a transition from either one to the other, the arrows overlap each other

![<screenshot>](https://user-images.githubusercontent.com/6538721/116161290-c6f2d980-a6f3-11eb-82ad-b9b816d49e4e.png)

**Comment by projetmbc** [comment]
Just click on an arrow and use the drag-and-drop feature.

**Comment by Anonym234** [comment]
> Just click on an arrow and use the drag-and-drop feature.

found that out, too
maybe a hint in the "how to use"-section would be nice

thank you !
